name: Quarkiverse Pre Release

on:
  pull_request:
    paths:
      - '.github/project.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-release:
    name: Pre-Release
    uses: quarkiverse/.github/.github/workflows/pre-release.yml@057cdb7218ecd8e486ecd6a7467c9cf4b857a03a # main
    secrets: inherit
